{% set data = load_setup_py_data() %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  noarch: python
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - pytest
    - numpy>=1.11
    - dask>=1.0
    - xarray
    - intake-xarray
    - zarr>=2
    - adlfs=0.5.5
    - h5netcdf>=0.8
    - intake
  host:
    - python
    - pip
  run:
    - python
    - numpy>=1.11
    - dask>=1.0
    - xarray
    - intake-xarray
    - zarr>=2
    - adlfs=0.5.5
    - h5netcdf>=0.8
    - intake
test:
  files:
    - "*"
  requires:
    - pytest
  commands:
    - pytest

about:
  home: https://github.com/informatics-lab/intake_informaticslab
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: SUMMARY

extra:
  recipe-maintainers:
    - theo.mccaie
