{% set data = load_setup_py_data() %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/informatics-lab/mogreps_uk_dataset.git

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - pytest
    - "numpy>=1.11"
    - 'dask>=1.0'
    - 'xarray'
    - 'zarr>=2'
    - 'adlfs'
    - 'h5netcdf>=0.8'
    - 'adlfs'
    - 'intake'
  host:
    - python
    - pip
  run:
    - python
    - "numpy>=1.11"
    - 'dask>=1.0'
    - 'xarray'
    - 'zarr>=2'
    - 'adlfs'
    - 'h5netcdf>=0.8'
    - 'adlfs'
    - 'intake'

test:
  imports:
    - mogreps_uk_dataset

about:
  home: HOMEPAGE
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: SUMMARY

extra:
  recipe-maintainers:
    - USERNAME
